/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.coe.info6205.userInterface;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author fanshujie
 */
public class WelcomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeJPanel
     */

    int[][] maze1 = new int[][] { 
            { 0, 0, 0, 0, 1, 0, 1, 3, 2 }, 
            { 1, 0, 1, 1, 1, 0, 1, 3, 1 },
            { 1, 0, 0, 1, 3, 3, 3, 3, 1 }, 
            { 3, 3, 3, 1, 3, 1, 1, 0, 1 }, 
            { 3, 1, 3, 3, 3, 1, 1, 0, 0 },
            { 3, 3, 1, 1, 1, 1, 0, 1, 1 }, 
            { 1, 3, 0, 1, 3, 3, 3, 3, 3 }, 
            { 0, 3, 1, 1, 3, 1, 0, 1, 3 },
            { 1, 3, 3, 3, 3, 1, 1, 1, 4 } 
    };
    int[][] maze2 = new int[][] { 
            { 0, 3, 3, 3, 2 }, 
            { 1, 3, 1, 1, 1 },
            { 1, 3, 0, 1, 0 }, 
            { 0, 3, 1, 1, 1 }, 
            { 1, 3, 3, 3, 4 } 
    };
    int[][] maze3 = new int[][] { 
            { 0, 0, 0, 0, 1, 0, 1, 3, 2 }, 
            { 1, 0, 1, 1, 1, 0, 1, 3, 1 },
            { 1, 0, 0, 1, 0, 0, 0, 3, 1 }, 
            { 0, 0, 0, 1, 0, 1, 1, 3, 1 }, 
            { 0, 1, 0, 0, 0, 1, 1, 3, 0 },
            { 0, 0, 1, 1, 1, 1, 0, 3, 1 },  
            { 1, 0, 0, 0, 0, 1, 1, 3, 4 } 
    };
    private JPanel CardSequenceJPanel;
    
        
    public WelcomeJPanel(JPanel CardSequenceJPanel) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maze1jButton = new javax.swing.JButton();
        maze2jButton = new javax.swing.JButton();
        maze3jButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to Maze Simulation");

        maze1jButton.setText("Maze1");
        maze1jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maze1jButtonActionPerformed(evt);
            }
        });

        maze2jButton.setText("Maze2");
        maze2jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maze2jButtonActionPerformed(evt);
            }
        });

        maze3jButton.setText("Maze3");
        maze3jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maze3jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maze3jButton)
                            .addComponent(maze2jButton)
                            .addComponent(maze1jButton))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(maze1jButton)
                .addGap(51, 51, 51)
                .addComponent(maze2jButton)
                .addGap(43, 43, 43)
                .addComponent(maze3jButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maze1jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maze1jButtonActionPerformed
        // TODO add your handling code here:
        RobotJPanel panel = new RobotJPanel(CardSequenceJPanel, maze1);
        CardSequenceJPanel.add("SimulationScreen", panel);
        CardLayout cardlayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardlayout.next(CardSequenceJPanel);

    }//GEN-LAST:event_maze1jButtonActionPerformed

    private void maze2jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maze2jButtonActionPerformed
        // TODO add your handling code here:
        RobotJPanel panel = new RobotJPanel(CardSequenceJPanel, maze2);
        CardSequenceJPanel.add("SimulationScreen", panel);
        CardLayout cardlayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardlayout.next(CardSequenceJPanel);
    }//GEN-LAST:event_maze2jButtonActionPerformed

    private void maze3jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maze3jButtonActionPerformed
        // TODO add your handling code here:
        RobotJPanel panel = new RobotJPanel(CardSequenceJPanel, maze3);
        CardSequenceJPanel.add("SimulationScreen", panel);
        CardLayout cardlayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardlayout.next(CardSequenceJPanel);
    }//GEN-LAST:event_maze3jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maze1jButton;
    private javax.swing.JButton maze2jButton;
    private javax.swing.JButton maze3jButton;
    // End of variables declaration//GEN-END:variables
}
